version: 2.1

orbs:
  node: circleci/node@4.7
  
jobs:
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: yarn install
      - run: yarn run eslint "**/*.js"    

workflows:
  snake_pipeline:
    jobs:
      - lint