version: 2.1

orbs:
  node: circleci/node@4.7
  
jobs:
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "./yarn.lock" }}
            - node-v1-
      - run:
          name: yarn
          command: yarn install
      - save_cache:
          key: node-v1-{{ checksum "./yarn.lock" }}
          paths:
            - node_modules
      - run: yarn install
      - run: yarn run eslint "**/*.js"    

workflows:
  snake_pipeline:
    jobs:
      - lint