version: 2.1

commands:
  checkout_and_build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "yarn.lock" }}
            - node-v1-
            - run:
                name: yarn
                command: yarn install
            - save_cache:
                key: node-v1-{{ checksum "yarn.lock" }}
                paths:
                  - ~/node_modules
            - run: yarn install

executors:
  docker-node:
    docker:
      - image: cimg/node:lts

orbs:
  node: circleci/node@4.7

jobs:
  lint:
    executor: docker-node
    steps:
      - checkout_and_build
      - run: yarn run eslint "**/*.js"
  ui-tests:
    executor: docker-node
    steps:
      - checkout_and_build
      - run: yarn test

workflows:
  snake_pipeline:
    jobs:
      - lint
      - ui-tests